version: "~> 1.0"

import:
  - source: netfoundry/ziti-ci:ziti-go-defaults.yml@v1
  - source: buildinfo.yml
    if: type != pull_request and branch != update-dependency

env:
  global:
    - GOX_OUTPUT="release/{{.Arch}}/{{.OS}}/{{.Dir}}"
script:
  - go get github.com/mitchellh/gox
  - CGO_ENABLED=true gox -os="linux" -arch="amd64" -output=$GOX_OUTPUT ./...
  - CGO_ENABLED=true gox -os="linux" -arch="arm64" -output=$GOX_OUTPUT ./...
  - CGO_ENABLED=true gox -os="darwin" -arch="amd64" -output=$GOX_OUTPUT ./...
  - CGO_ENABLED=true gox -os="windows" -arch="amd64" -output=$GOX_OUTPUT ./...
  - find release