version: "~> 1.0"

import:
  - source: netfoundry/ziti-ci:go-defaults.yml@v1
  - source: netfoundry/ziti-ci:ziti-ci.yml@v1
  - source: netfoundry/ziti-ci:git-setup.yml@v1
  - source: netfoundry/ziti-ci:versioning.yml@v1
    if: type != pull_request

env:
  global:
    - GOX_OUTPUT="release/{{.Arch}}/{{.OS}}/{{.Dir}}"

matrix:
  include:
    - os: linux
      arch: amd64
      env: GOX_OS=linux
    - os: linux
      arch: arm64
      env: GOX_OS=linux
    - os: mac
      env: GOX_OS=darwin
    - os: windows
      env: GOX_OS=windows

script:
  - go get github.com/mitchellh/gox
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-tunnel/cmd/ziti-tunnel
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-controller
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti/cmd/ziti
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-fabric-gw
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-enroller
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-fabric
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-fabric-test
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./ziti-router
