version: "3.3"
services:
    ziti-tunnel:
        image: netfoundry/ziti-tunnel:local
        build:
            context: .
            args:
                ZITI_VERSION: 0.15.2 
        volumes:
        - .:/netfoundry
        network_mode: host
        cap_add:
        - NET_ADMIN
        environment:
        - NF_REG_NAME=my-ziti-identity-file
#        command: run --resolver udp://127.0.0.123:53
