fields_under_root: true
fields:
  build_number: ${build_number}
  ziti_version: ${ziti_version}

filebeat.inputs:
  # New ziti metrics with identity/service attribution
  - type: log
    enabled: true
    paths:
      - /var/log/ziti/utilization*.log
    close_timeout: 5m
    tags: ["ztutilization"]

  # New ziti metrics with identity/service attribution
  - type: log
    enabled: true
    paths:
      - /var/log/ziti/utilization*.log
    close_timeout: 5m
    tags: ["ztutilization"]

  - type: log
    enabled: true
    paths:
      - /var/log/ziti/controller.log*
      - /var/log/ziti/router.log*
      - /var/log/ziti/fabric.log*
    # If implementing multiline support in the future,
    # or adding other clean_* or close_* directives,
    # please see the docs for this setting to understand
    # how this setting affects and interacts with them.
    # https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-close-timeout
    close_timeout: 5m
    exclude_files:
      - '\.gz$'
    tags: ["ztlogs"]

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://ziti-build-metrics.es.us-east-1.aws.found.io:443"] #https://ziti-build-metrics.kb.us-east-1.aws.found.io:443

  # Optional protocol and basic auth credentials.
  protocol: "https"
  username: "beats_agent" #beats_agent
  password: "s6eHpUU5K2774xCD" #s6eHpUU5K2774xCD
  index: 'zt-%{[agent.version]}-%{+yyyy.MM.dd}'