name: Build and Run db-creation Golang

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pete-iPerf branch
        uses: actions/checkout@v3
        with:
          repository: padibona/fablab
          ref: refs/heads/pete-iperf

      - name: Checkout DB-Creation branch
        uses: actions/checkout@v3
        with:
          repository: padibona/ziti
          ref: refs/heads/db-creation

      - name: Build and Run
        run: |
          cd ~/ziti/zititest/models/db-creation
          go build -o db-creation main.go
          ./db-creation create db-creation
          ./db-creation up
          ./db-creation dispose
