name: Build and Run db-creation Golang

on:
  push:
    branches:
      - db-creation

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build and Run
        run: |
          go build -o db-creation main.go
          ./db-creation
