name: fablab db-creation workflow

on:
  push:
    branches:
      - main
env:
  GOFLAGS: "-trimpath"
  GOX_OUTPUT: "release/{{.Arch}}/{{.OS}}/{{.Dir}}"
  GOX_TEST_OUTPUT: "test/{{.Arch}}/{{.OS}}/bin/{{.Dir}}"
  AWS_ACCESS_KEY_ID: ${{ secrets.FABLAB_AWS_EC2_PETE_D_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.FABLAB_AWS_EC2_PETE_D_SECRET }}
  AWS_DEFAULT_REGION: "us-east-1"
  
jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pete-iPerf branch
        uses: actions/checkout@v3
        with:
          repository: openziti/fablab
          ref: refs/heads/pete-iperf
      
      - name: Checkout DB-Creation branch
        uses: actions/checkout@v3
        with:
          repository: padibona/ziti
          ref: refs/heads/main
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'

      - name: Build and Run
        run: |
          cd zititest/models/db-creation
          go build -o db-creation main.go
          ./db-creation create db-creation
          ./db-creation up
          
          
          
          
