name: Jenkins Smoketest
on:
  workflow_call:
    inputs:
      ziti_version:
        description: 'Semantic Version from `ziti-ci -q get-current-version`'
        type: string
        required: false
  workflow_dispatch:
    inputs:
      ziti_version:
        description: 'Semantic Version from `ziti-ci -q get-current-version`'
        type: string
        required: false

jobs:
  jenkins-smoketest:
    runs-on: ubuntu-latest
    name: POST Webhook to Jenkinstest
    steps:
      - name: Trigger Smoketest
        if: ${{ env.ZITI_JENKINS_WEBHOOK_URL != null }}
        env:
          ZITI_JENKINS_WEBHOOK_URL: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
        uses: openziti/ziti-webhook-action@v2
        with:
          ziti-id: ${{ secrets.ZITI_JENKINS_IDENTITY }}
          webhook-url: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.ZITI_JENKINS_WEBHOOK_SECRET }}
          data: |
            ziti-version=${{ github.event.inputs.ziti_version }}
